# Generated by Django 4.1.7 on 2023-02-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=10)),
                ('phonenumber', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_on'],
            },
        ),
    ]
