# Generated by Django 4.1.7 on 2023-02-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=10)),
                ('phonenumber', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_on'],
            },
        ),
        migrations.DeleteModel(
            name='ContactData',
        ),
    ]
